export enum GetThirdDiscountsActionTypes {
  REQUESTED_GET_THIRD_DISCOUNTS = "REQUESTED_GET_THIRD_DISCOUNTS",
  RECIVED_GET_THIRD_DISCOUNTS = "RECIVED_GET_THIRD_DISCOUNTS",
  FAILED_GET_THIRD_DISCOUNTS = "FAILED_GET_THIRD_DISCOUNTS",
}
