export enum GetVehicleTypesActionTypes {
  REQUESTED_GET_VEHICLE_TYPES = "REQUESTED_GET_VEHICLE_TYPES",
  RECIVED_GET_VEHICLE_TYPES = "RECIVED_GET_VEHICLE_TYPES",
  FAILED_GET_VEHICLE_TYPES = "FAILED_GET_VEHICLE_TYPES",
}
