export enum GetInsuranceCompaniesActionTypes {
  REQUESTED_GET_INSURANCE_COMPANIES = "REQUESTED_GET_INSURANCE_COMPANIES",
  RECIVED_GET_INSURANCE_COMPANIES = "RECIVED_GET_INSURANCE_COMPANIES",
  FAILED_GET_INSURANCE_COMPANIES = "FAILED_GET_INSURANCE_COMPANIES",
}
